# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocationEvent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13LocationEvent.proto\"M\n\x14LocationEventMessage\x12\x10\n\x08personId\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\x05\x32\x45\n\x0bItemService\x12\x36\n\x06\x43reate\x12\x15.LocationEventMessage\x1a\x15.LocationEventMessageb\x06proto3')



_LOCATIONEVENTMESSAGE = DESCRIPTOR.message_types_by_name['LocationEventMessage']
LocationEventMessage = _reflection.GeneratedProtocolMessageType('LocationEventMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONEVENTMESSAGE,
  '__module__' : 'LocationEvent_pb2'
  # @@protoc_insertion_point(class_scope:LocationEventMessage)
  })
_sym_db.RegisterMessage(LocationEventMessage)

_ITEMSERVICE = DESCRIPTOR.services_by_name['ItemService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONEVENTMESSAGE._serialized_start=23
  _LOCATIONEVENTMESSAGE._serialized_end=100
  _ITEMSERVICE._serialized_start=102
  _ITEMSERVICE._serialized_end=171
# @@protoc_insertion_point(module_scope)
